# Generated by Django 6.1 on 2026-09-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_cliente_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
